#!/bin/sh
set -e

echo "php-cs-fixer pre commit hook started"

PHP_CS_FIXER="vendor/bin/php-cs-fixer"
PHP_CS_CONFIG=".php-cs-fixer.dist.php"
CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')

if [ -n "$CHANGED_FILES" ]; then
    $PHP_CS_FIXER fix --config "$PHP_CS_CONFIG" $CHANGED_FILES --dry-run --diff;
fi

echo "php-cs-fixer pre commit hook finished"
